version: "3.7"
services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
  app:
    image: blogtest
    ports:
      - "8080:8080"
    hostname: blogie
volumes:
  conf:
  vhost:
  html:
  certs:

